#!/bin/bash

#for var in 1 2 3 4 5 6 7 8 9 10
#do
#       if [ $var -eq 5 ]
#       then
#         break 
 #      fi
  #     echo "number: $var"
#done

#var1=1
#while [ $var1 -lt 10 ]
#do
 #   if [ $var1 -eq 5 ]
  #  then
   #  break 
    #fi
   # echo "Iteration: $var1"
   # var1=$[ $var1 + 1 ]
#donei
for (( a = 1; a < 4; a++ ))
do
    echo "Outer loop: $a"
    for (( b = 1; b < 100; b++ ))
        do
         if [ $b -gt 4 ]
          then
            break 2 
         fi
         echo "Inter loop: $b"
        done
done
